{{ if ne .Values.environment "ci" }}
{{ range .Values.domains -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "reverse-proxy.name" . }}
  namespace: default
spec:
  secretName: {{ include "reverse-proxy.tlsName" . }}
  issuerRef:
    name: letsencrypt
  dnsNames:
  - {{ .origin }}
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - {{ .origin }}
---
{{ end -}}
{{ end }}
