{{ range .Values.domains -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ .origin }}"
  name: {{ include "reverse-proxy.name" . }}
spec:
  tls:
  - hosts:
      - {{ .origin }}
    secretName: {{ include "reverse-proxy.tlsName" . }}
  rules:
  - host: {{ .origin }}
    http:
      paths:
      - backend:
          serviceName: {{ include "reverse-proxy.name" . }}
          servicePort: 80
        path: /(.*)
---
{{ end -}}
