domains:
- id: kusama-userguide
  origin: guide.kusama.network
  target: kusama-userguide.readthedocs.io
- id: url1800
  origin: url1800.web3.foundation
  target: sendgrid.net


environment: production
